name: meccpma
description: A cross platform mobile application made with Flutter for Mahindra Ecole Centrale

dependencies:
  flutter:
    sdk: flutter
  dictionary: "^0.2.4"
  flutter_statusbarcolor: any
  image_carousel: "^0.4.1"
  flutter_custom_tabs: "^0.2.0"


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/mec.png
    - assets/mec.jpg
    - assets/mec_side.jpg
    - assets/outlook.png
    - assets/atmec.jpg
    - assets/antiragging.jpg
    - assets/tedx.jpg
    - assets/mec1.jpg
    - assets/mec2.jpg
    - assets/mec3.jpg
    - assets/pupp.jpg
    - assets/Top-10-Moments-of-2015.png
    - assets/31-March-1.1-min.jpg
    - assets/Civil-Engineering-min.jpg
    - assets/MEC_Blog_Header1.jpg
    - assets/twitter.png
    - assets/facebook.png
    - assets/LinkedIn.png
    - assets/r1.jpg
    - assets/r2.jpg
    - assets/r3.jpg
    - assets/r4.jpg
    - assets/r6.jpg

  fonts:
    - family: Times New Roman
      fonts:
        - asset: fonts/Times New Roman.ttf



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
